Social Login
vector-im/element-android pull request #2484
Opened 2020-12-03 10:05 UTC by BillCarsonFr

Fixes #2452
Fixes #1933

<img width="383" alt="image" src="https://user-images.githubusercontent.com/9841565/100994721-2d196d00-3557-11eb-99a9-b887052569e9.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/9841565/100994847-520de000-3557-11eb-8920-6d903ef97892.png">

2020-12-04 08:09 UTC, BillCarsonFr commented
@bmarty regarding the known server completion, can you please advise if i should move the HomeServerHistoryService somewhere else? and should i refactor RawModule and move global DB somewhere else?

2020-12-07 13:36 UTC, bmarty requested changes
I made a first static review.

2020-12-07 13:36 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/IdentityProvider.kt
> +         * */
bad formatting

2020-12-07 13:36 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/IdentityProvider.kt
> +        @Json(name = "icon") val icon: String?
Maybe rename to `iconUrl`?

2020-12-07 13:36 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/IdentityProvider.kt
> +data class IdentityProvider(
I suspect it could be a confusing name because of the Identity Service. Maybe rename to `SsoParameters` or `SsoDetails`?

2020-12-07 13:36 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt
> +        val identityProvider: List<IdentityProvider>?
Please rename to `identityProviders` (or any other name if the type is renamed, but ending with an `s`)

2020-12-07 13:36 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt
> +        val identityProvider: List<IdentityProvider>?
Update the docs `signin.md`, or create a dedicated doc for SSO?

2020-12-07 13:36 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/raw/GlobalRealmMigration.kt
> +                .addField(KnownServerUrlEntityFields.URL, String::class.java)
I think you should declare that it's used as a primary key, or we will have crash

2020-12-07 13:36 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/raw/RawModule.kt
> +    abstract fun bindHomeServerHistoryService(service: DefaultHomeServerHistoryService): HomeServerHistoryService
Please either create a new Module or rename this one to something more generic.

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
> +//    fun bindLoginSignUpSignInSsoFragment(fragment: LoginSignUpSignInSsoFragment): Fragment
Please cleanup

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/AbstractSSOLoginFragment.kt
> +        val hasSSO = withState(loginViewModel) { it.loginMode.hasSso() }
I think `hasSSO` could be passed as a Fragment parameter, since it's not live.

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginAction.kt
> +    data class SetupSsoForSessionRecovery(val homeServerUrl: String, val deviceId: String, val identityProvider: List<IdentityProvider>?) : LoginAction()
identityProvider**s**

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
> +            is Stage.Terms -> addFragmentToBackstack(R.id.loginFragmentContainer,
Please revert change on the formatting, I know AS does not help on this :/

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
> +    }
Please remove

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
> +                SignMode.SignIn -> R.string.login_connect_to
revert formatting

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginServerSelectionFragment.kt
> +            loginViewModel.handle(LoginAction.PostViewEvent(LoginViewEvents.OnLoginFlowRetrieved(state.loginMode is LoginMode.Sso)))
use `hasSso()` extension instead?

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginServerUrlFormFragment.kt
> +            loginViewModel.handle(LoginAction.PostViewEvent(LoginViewEvents.OnLoginFlowRetrieved(state.loginMode is LoginMode.Sso)))
use `hasSso()`?

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
> +            homeServerHistoryService.addHomeServerToHistory("http://10.0.2.2:8080")
I would not modify the DB here, but just add this debug URL to the list returned by `getKnownServersUrls()`

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
> +            is LoginAction.PostViewEvent -> _viewEvents.post(action.viewEvent)
please revert fomatting

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
> +                rememberHomeServer(finalLastAction.homeServerUrl)
Should it be better to remember the homeserver only if it appears to be valid? i.e. once the user actually creates a session?

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/SocialLoginButtonsView.kt
> +                        "google"   -> {
Create some constants SDK side for those hard-coded values?

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutController.kt
> +                    LoginMode.Password          -> {
Format...

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/res/layout/fragment_login.xml
> +                    app:signMode="signin"
could be `tools:signMode` I think

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/res/layout/fragment_login.xml
> +                android:clipChildren="false"
Are those 2 attributes about "clipping" really useful?

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/res/layout/fragment_login_signup_signin_selection.xml
> +                android:clipChildren="false"
same remark about clip attributes

2020-12-07 13:36 UTC, bmarty commented on vector/src/main/res/values/styles_riot.xml
> +    </style>
Dark and light variants should be moved to new dedicated files for light and dark styles, which will allow comparison of those files.

2020-12-14 13:08 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/IdentityProvider.kt
> +         * */
done

2020-12-14 13:09 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/IdentityProvider.kt
> +        @Json(name = "icon") val icon: String?
Done

2020-12-14 13:15 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/IdentityProvider.kt
> +data class IdentityProvider(
Renamed to `SsoIdentityProvider`

2020-12-14 13:16 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt
> +        val identityProvider: List<IdentityProvider>?
(Done?)

2020-12-14 13:17 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt
> +        val identityProvider: List<IdentityProvider>?
will do it later

2020-12-14 13:30 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/raw/GlobalRealmMigration.kt
> +                .addField(KnownServerUrlEntityFields.URL, String::class.java)
Done, and required too

2020-12-14 14:08 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/raw/RawModule.kt
> +    abstract fun bindHomeServerHistoryService(service: DefaultHomeServerHistoryService): HomeServerHistoryService
moved to AuthModule

2020-12-14 14:09 UTC, bmarty commented on vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
> +//    fun bindLoginSignUpSignInSsoFragment(fragment: LoginSignUpSignInSsoFragment): Fragment
done

2020-12-14 14:09 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/AbstractSSOLoginFragment.kt
> +        val hasSSO = withState(loginViewModel) { it.loginMode.hasSso() }
may be refactored later

2020-12-14 14:10 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginAction.kt
> +    data class SetupSsoForSessionRecovery(val homeServerUrl: String, val deviceId: String, val identityProvider: List<IdentityProvider>?) : LoginAction()
Done

2020-12-14 14:11 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
> +            is Stage.Terms -> addFragmentToBackstack(R.id.loginFragmentContainer,
Done

2020-12-14 14:12 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
> +    }
Done

2020-12-14 14:12 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
> +                SignMode.SignIn -> R.string.login_connect_to
Done

2020-12-14 14:13 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
> +            is LoginAction.PostViewEvent -> _viewEvents.post(action.viewEvent)
Done

2020-12-14 14:14 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutController.kt
> +                    LoginMode.Password          -> {
Done

2020-12-14 14:17 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginServerSelectionFragment.kt
> +            loginViewModel.handle(LoginAction.PostViewEvent(LoginViewEvents.OnLoginFlowRetrieved(state.loginMode is LoginMode.Sso)))
I removed this now unused param

2020-12-14 14:17 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginServerUrlFormFragment.kt
> +            loginViewModel.handle(LoginAction.PostViewEvent(LoginViewEvents.OnLoginFlowRetrieved(state.loginMode is LoginMode.Sso)))
param removed

2020-12-14 14:23 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
> +            homeServerHistoryService.addHomeServerToHistory("http://10.0.2.2:8080")
Done

2020-12-14 14:33 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
> +                rememberHomeServer(finalLastAction.homeServerUrl)
Done

2020-12-14 14:42 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/login/SocialLoginButtonsView.kt
> +                        "google"   -> {
Done

2020-12-14 14:43 UTC, bmarty commented on vector/src/main/res/layout/fragment_login.xml
> +                android:clipChildren="false"
Removed

2020-12-14 14:44 UTC, bmarty commented on vector/src/main/res/layout/fragment_login_signup_signin_selection.xml
> +                android:clipChildren="false"
Removed

2020-12-14 14:45 UTC, bmarty commented on vector/src/main/res/layout/fragment_login.xml
> +                    app:signMode="signin"
Done

2020-12-14 17:17 UTC, bmarty commented on vector/src/main/res/values/styles_riot.xml
> +    </style>
I moved the new styles in a dedicated file

2020-12-14 17:17 UTC, bmarty approved these changes

2020-12-14 17:19 UTC, merged