Feature/fga/voip switch call and transfer init
vector-im/element-android pull request #2575
Opened 2020-12-22 16:26 UTC by ganfra

This PR introduces:
- Call switching, so you can have 1 active call and 1 on hold (or 2 on hold).
- Call transfer init (reusing user list fragment)
- Elapsed time on call

It also fixes a bunch of issues.

2020-12-28 16:12 UTC, bmarty requested changes
Nice work. A few remarks and questions about the implementation.

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/res/values/strings.xml
> +    <string name="call_only_multiple_paused">%1$d paused calls</string>
done

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/res/values/strings.xml
> +    <string name="call_active_and_multiple_paused">1 active call (%1$s) · %2$d paused calls</string>
done

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt
> -                    myUserId = session.myUserId,
It's not used at all, I forgot to remove it entirely from the state

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomActivity.kt
> +                            showInviteActions = false
Yes, it was just used to know if we show invite actions. So replaced it directly by the bool

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/RoomSummaryHolder.kt
>  class RoomSummaryHolder @Inject constructor() {
done

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCallManager.kt
> +        fun onCurrentCallChange(call: WebRtcCall?) {}
I think it's ok on for listeners...

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/java/im/vector/app/features/call/transfer/CallTransferViewModel.kt
> +        }
Done

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/java/im/vector/app/features/call/transfer/CallTransferViewModel.kt
> +        val webRtcCall = callManager.getCallById(initialState.callId)
Done

2021-01-04 17:55 UTC, ganfra commented on vector/src/main/java/im/vector/app/core/di/ScreenComponent.kt
> +    fun inject(callTransferActivity: CallTransferActivity)
Done

2021-01-08 10:51 UTC, bmarty approved these changes
Thanks for the update, you can merge into your main branch whenever you want to!

2021-01-08 10:51 UTC, bmarty commented on vector/src/main/java/im/vector/app/core/di/VectorComponent.kt
> +    fun roomSummaryHolder(): RoomSummariesHolder
Not a big deal but this should also have to be renamed.

2021-01-08 11:09 UTC, merged