Fix order of sending/undelivered messages
vector-im/element-android pull request #2663
Opened 2021-01-13 08:58 UTC by onurays

Fixes #729

2021-01-13 10:51 UTC, ganfra requested changes

2021-01-13 10:51 UTC, ganfra commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryEventsHelper.kt
> +    fun getLatestPreviewableEvent(realm: Realm, roomId: String, includeSending: Boolean = true): TimelineEventEntity? {
Please don't change this method. If you don't need sending then this is not the latestPreviewable...

2021-01-13 10:51 UTC, ganfra commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
> +        return (buildSendingEvents() + builtEvents.toList()).sortedByDescending { it.root.originServerTs }
We shouldn't rely on ts to sort events

2021-01-13 10:56 UTC, ganfra commented
I don't understand exactly which case you try to fix here

2021-02-22 08:59 UTC, ShadowJonathan commented
Copy-paste from #729:

> When i was poking around in the internals, it seems to be that element has a global send queue, maybe for this initialisation it's better if there's an ad-hoc queue per room? To make sure events sent in other rooms dont "block" on a large file sent earlier in one room.

2021-11-19 10:18 UTC, bmarty commented
Stale PR, I close it, let's try to fix the original issue in another way

2021-11-19 10:18 UTC, closed without merging