Add invite by email screen in create space flow
vector-im/element-android pull request #3976
Opened 2021-09-07 12:15 UTC by BillCarsonFr

Fixes #3678 (add invite by mail screen for private space)
Fixes #3945 Remove the "Teammate spaces aren't quite ready" bottom sheet

When creating a new private team space, a screen is added where you can add up tp 3 emails. There is no integration with contact book for now. 
- If no emails entered you can skip this step
- If one the email is malformed an inline error is displayed and you have to fix in order to continue
- If no Identity Server is defined, user will see a message and an action to open discovery settings 

<img width="231" alt="image" src="https://user-images.githubusercontent.com/9841565/132342602-7ed8bede-ec55-4d81-94fc-e4579407aedd.png">

<img width="357" alt="image" src="https://user-images.githubusercontent.com/9841565/132342698-7107f796-75d0-4e0c-bf3a-f6b3e1d28c1d.png">

<img width="232" alt="image" src="https://user-images.githubusercontent.com/9841565/132342745-2844dfaf-7890-4a0d-927c-612e2a71a472.png">

2021-09-07 13:14 UTC, BillCarsonFr commented
Full flow when you don't have IDS
<img width="964" alt="image" src="https://user-images.githubusercontent.com/9841565/132350889-7a950b7e-3397-4f2b-a2fa-a77ddce03e1f.png">

2021-09-08 10:17 UTC, bmarty requested changes
(static review) 2 small remarks

2021-09-08 10:17 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceAdd3pidInvitesFragment.kt
> +        epoxyController.listener = this
Add cleanup in `onDestroyView()`

2021-09-08 10:17 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModel.kt
> +        identityService.addListener(identityServerManagerListener)
removeListener :)

2021-09-14 13:24 UTC, BillCarsonFr commented on vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceAdd3pidInvitesFragment.kt
> +        epoxyController.listener = this
Done

2021-09-14 13:24 UTC, BillCarsonFr commented on vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModel.kt
> +        identityService.addListener(identityServerManagerListener)
🙃

2021-09-14 18:18 UTC, bmarty approved these changes
Thanks for the update.

2021-09-14 18:18 UTC, merged