Navigation | New Home tab to priorize all unread
vector-im/element-android pull request #4010
Opened 2021-09-14 08:04 UTC by BillCarsonFr

App Navigation modification.

This PR introduces a new Home Tab, in this tab you will find all important things you need to read first in a less busy and more compact layout so you can see more at once (one line per room with no last message preview or timestamp) .

It is combining rooms and people into one list, in order to stop people having to change tabs to check on unread rooms/people.

![image](https://user-images.githubusercontent.com/9841565/133219396-30bb34bb-a13f-414f-8f05-51e75ca86b6b.png)

The Home tab contains in order
- Invites if any
- Your Favorites for quick access
- DMs with notifications
- Rooms with notifications
- Other Rooms sorted by unread first
- Other Dms
- Suggested rooms of space if any

The existing DM tabs and Room Tabs are modified a bit, they won't show favorite or invites anymore as they will be on Home already. They will continue to display rooms in last activity order.

2021-09-14 14:31 UTC, jwsp1 commented
General thought: I don't see the need to separate rooms into categories like Favorites, Unread DM, Unread Rooms, DM, Rooms, and Low Priority. It just wastes valuable space which could be used to show a preview of the latest message. 

If this is supposed to fix #650, then it is not quite what people wanted.
The most simple style for most users would be to remove all tabs and show rooms in this order:
- Favorites (always pinned to top), 
- then DM/Rooms ordered by time of latest message,
- then Low Priority (always pinned to bottom).

2021-09-16 14:48 UTC, BillCarsonFr commented
Following feedbacks from this (and related issues), I added a new Preference that allows users to select their preffered layout

<img width="224" alt="image" src="https://user-images.githubusercontent.com/9841565/133633349-59819f97-57d0-4caf-8f50-308ba93b5230.png">

Pro Layout will have 3 tabs, Home/Dms/Rooms .
Home will put every rooms/dms with notification on top, and will replace the previous optional 3rd tab (notifications only).
Home will have Invites / Favorites and they won't be repeated in other tabs

Simple layout will have no tabs, so all your rooms in one list ordered by activity. 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/9841565/133633903-30a8fcd1-455f-401f-903c-a5e9233a1f83.png">

2021-09-29 15:13 UTC, bmarty requested changes
First remarks:
- This PR has to be rebased.
- Also please ensure that the sanity test is still passing (it will need some update)
- I will do a full review later

2021-10-05 10:25 UTC, bmarty reviewed
Thanks for doing this, I'm sure it will be really appreciated.
Please see my comments

2021-10-05 10:25 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt
> +            copy(layoutMode = vectorPreferences.getLayoutMode())
setState only if the value is not the same? It's maybe done internally by MvRx, not sure.

2021-10-05 10:25 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
> +        return defaultPrefs.getString(SETTINGS_LAYOUT_MODE, LayoutMode.PRODUCTIVITY.name).let {
Default is PRODUCTIVITY? I would say SIMPLE would be better, or maybe reuse the setting `SETTINGS_LABS_UNREAD_NOTIFICATIONS_AS_TAB`, if true -> PRODUCTIVITY

2021-10-05 10:25 UTC, bmarty commented on vector/src/main/res/drawable/ic_pro_layout.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
rename the two drawable vectors to ensure they have a common prefix: `ic_layout_pro` and `ic_layout_simple`. Also those are not really icon, so maybe `setting_layout_pro` and `setting_layout_simple` would be better names

2021-10-05 10:25 UTC, bmarty commented on vector/src/main/res/drawable/ic_simple_layout.xml
> +      android:fillColor="#C1C6CD"
does it render well in dark theme?

2021-10-05 10:25 UTC, bmarty commented on vector/src/main/res/layout/preference_app_choose_layout.xml
> +
cleanup?

2021-12-07 07:53 UTC, AnisTaluqdar commented
Still, waiting for it. 🥺

2021-12-08 11:05 UTC, Flam3z commented
We can only hope and be patient :)

2021-12-10 10:44 UTC, kojid0 commented
> The merging of this PR has been delayed, the changes it brings require more internal discussions

I understand that the Design Team might wand to unify the look&feel between Android&iOS, but this PR is really necessary for simplicity. 
Currently, you will miss reading messages if you forget to frequently look in both tabs. I have two users where I see that they respond in rooms but not in DMs because they don't check both places. 
Please merge this (as it's a working solution for now) and get back to it later if necessary.

2022-02-28 13:14 UTC, bmarty commented
Let's remove this PR, we will iterate with IA later.

2022-02-28 13:14 UTC, closed without merging

2022-05-03 08:19 UTC, kojid0 commented
Can you please link the subsequent issue / PR? 
Still waiting for this... Many of my friends miss new messages because they don't look in both tabs.