Remove redundant heading from bug report issue form
vector-im/element-android pull request #4076
Opened 2021-09-24 16:14 UTC by opusforlife2

### Pull Request Checklist

- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog

The issue form currently generates a bug report that contains the "What happened?" heading twice. See https://github.com/vector-im/element-android/issues/4047#issue-1001300890.

This PR edits the culprit heading and its subheadings to remove the redundancy and clarify what is meant.

2021-09-24 16:19 UTC, opusforlife2 commented
@bmarty @kittykat Is it okay now?

2021-09-24 18:35 UTC, bmarty approved these changes
OK for me

2021-09-28 07:55 UTC, ouchadam approved these changes

2021-09-28 07:57 UTC, ouchadam commented
@bmarty should we also sync this with iOS? https://github.com/vector-im/element-ios/blob/develop/.github/ISSUE_TEMPLATE/bug.yml

2021-09-28 08:23 UTC, kittykat requested changes

2021-09-28 08:24 UTC, kittykat commented
> @bmarty should we also sync this with iOS? https://github.com/vector-im/element-ios/blob/develop/.github/ISSUE_TEMPLATE/bug.yml

Yes, please submit the same changes for element-ios and element-web (which has two forms) after this one is finalised and add me as the reviewer for those

2021-10-01 18:57 UTC, bmarty reviewed
@opusforlife2 will you update this PR? Else I'm afraid we will close it.

2021-10-01 18:57 UTC, bmarty commented on changelog.d/4076.misc
> +Remove redundant heading from bug report issue form
This is not really corresponding to the (new) change.

2021-10-02 07:14 UTC, opusforlife2 commented on .github/ISSUE_TEMPLATE/bug.yml
> +      label: Intended vs. Actual Result
Done. Is it so that those who use online translators get better translations?

2021-10-02 07:18 UTC, opusforlife2 commented
> Yes, please submit the same changes for element-ios and element-web (which has two forms) after this one is finalised and add me as the reviewer for those

@kittykat Is this addressed to me?

> will you update this PR? Else I'm afraid we will close it.

@bmarty I'm here on weekends only. Since you guys have the weekend off, there is bound to be a mismatch between our work times, sadly.

2021-10-03 09:24 UTC, bmarty commented
@opusforlife2 thanks for the update!

2021-10-03 09:26 UTC, bmarty commented
> > Yes, please submit the same changes for element-ios and element-web (which has two forms) after this one is finalised and add me as the reviewer for those
> 
> @kittykat Is this addressed to me?

I think so, yes :)

> 
> > will you update this PR? Else I'm afraid we will close it.
> 
> @bmarty I'm here on weekends only. Since you guys have the weekend off, there is bound to be a mismatch between our work times, sadly.

Sure, sorry for my unnecessary pressure. We are trying to reduce the number of opened (and sometimes staled) PRs.

2021-10-03 09:27 UTC, bmarty commented
I let @kittykat approve and merge the PR

2021-10-05 11:17 UTC, kittykat approved these changes

2021-10-05 11:22 UTC, kittykat commented
@opusforlife2 I'm trying out slightly different wording in element-web, can you have a look at that and see what you think? Please submit a PR for element-ios and add me as a reviewer :)

2021-10-05 13:35 UTC, merged