Voice Message - Draft support
vector-im/element-android pull request #4237
Opened 2021-10-13 13:29 UTC by onurays

If a user leaves the room detail screen without sending or deleting the ongoing voice message record then we need to save this record as a draft message and render it again in playback mode when the user enters the room detail screen again.

- [x] Extend the draft service to support multiple message types
- [x] Listen onPause of the RoomDetailFragment and save the VM draft if the recording is active
- [x] Show voice message in playback mode
- [x] Initialize voice message view with the saved draft
- [x] Delete the cache file if the user decides to delete or send the recording 

EDIT
Fixes #3922

2021-11-01 08:38 UTC, onurays commented on vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
> +    private fun renderRegularMode(content: String, messageType: String) {
Done.

2021-11-04 09:45 UTC, bmarty commented on matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
> +
This will be a problem for those who are already on version 19. In this case you should create a version 20.

2021-11-04 10:50 UTC, bmarty requested changes
I'm sorry I think this has to be modified.
I would like the voice messages to be saved as draft by the SDK, using `DraftService`.
It will simplify the code I think and make it more robust, by following our current architecture.
What do you think about it?

2021-11-10 09:19 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
> +            _viewEvents.post(RoomDetailViewEvents.SaveDraft(null, MessageType.MSGTYPE_TEXT))
weird arch

2021-11-10 10:21 UTC, ouchadam commented
going to close this PR whilst working on it

2021-11-10 10:21 UTC, closed without merging