Remove deprecated restricted lab option
vector-im/element-android pull request #4889
Opened 2022-01-10 09:41 UTC by BillCarsonFr

Removes the deprecated use experimental restricted join rule lab option

2022-01-10 10:29 UTC, bmarty requested changes
Please do not touch the translated strings, I do not want to have conflict with Weblate.
See https://github.com/vector-im/element-android/blob/main/CONTRIBUTING.md#removing-existing-strings for more details

2022-01-10 13:07 UTC, BillCarsonFr commented
> Please do not touch the translated strings, I do not want to have conflict with Weblate. See https://github.com/vector-im/element-android/blob/main/CONTRIBUTING.md#removing-existing-strings for more details

Updated

2022-01-10 13:43 UTC, bmarty requested changes
See my remark also the CI is not happy:
`w: /workdir/vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt: (58, 55): Parameter 'vectorPreferences' is never used`

2022-01-10 13:54 UTC, BillCarsonFr commented on vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt
> +//            HomeServerCapabilities.RoomCapabilitySupport.SUPPORTED_UNSTABLE -> vectorPreferences.labsUseExperimentalRestricted()
yeah, I hesitated a bit but will remove now (done)

2022-01-10 17:39 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt
> +//            HomeServerCapabilities.RoomCapabilitySupport.SUPPORTED_UNSTABLE -> vectorPreferences.labsUseExperimentalRestricted()
Still a change to do here

2022-01-11 08:38 UTC, BillCarsonFr commented on vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt
> +//            HomeServerCapabilities.RoomCapabilitySupport.SUPPORTED_UNSTABLE -> vectorPreferences.labsUseExperimentalRestricted()
thx, updated (+ rebase)

2022-01-11 08:47 UTC, bmarty approved these changes
Thanks for the update. I will squash and merge.

2022-01-11 09:01 UTC, merged

2022-01-11 09:40 UTC, bmarty commented on changelog.d/4889.removal
> +Remove deprecated experimental restricted space lab option
FYI: using `removal` extension is reserved for changes in the SDK. For this change `misc` would have been better. (I am seeing that when doing the release, so I will update the changelog manaully, no worries)