#4164 Display a notification if there is unsent message(s)
vector-im/element-android pull request #5287
Opened 2022-02-22 07:26 UTC by ahmed-radhouane

Signed-off-by: Ahmed Radhouane Belkilani <arbelkilani@gmail.com>

 
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- update postTask in EventSenderProcessorCoroutine.kt in order to catch exception and return new type of Cancelable
- adding new state MessageUnsentException to handle the new exception state and display the notification.
- adding the new notification in NotificationUtils.kt in order to handle the different messages depending on exception type.
- throw exception from related tasks.
- adding new strings resources depending on exception type.
- increase max lines to 2800 lines.
- adding changelog file.

## Motivation and context

After sending message and in case of error, we should show a notification informing user of cause of error. 

## Screenshots / GIFs
Network Error | Server Error | Unknown Error
--- | --- | ---
<img width="384" alt="Capture d’écran 2022-02-21 à 17 37 33" src="https://user-images.githubusercontent.com/73594434/155082697-c35c1b30-88d6-4b79-a2b8-aa7d150ddeb3.png"> | <img width="382" alt="Capture d’écran 2022-02-21 à 17 37 02" src="https://user-images.githubusercontent.com/73594434/155082740-c36863bf-6d6b-4882-b114-8e5ae1669075.png"> | <img width="383" alt="Capture d’écran 2022-02-21 à 17 40 13" src="https://user-images.githubusercontent.com/73594434/155082761-e4ab82fd-e72c-48b2-ae87-4c91f7b7577f.png">

## Tests

- Access to Room or DM
- Send a message with bad internet connection
- A notification appear if message was not sent. 

## Tested devices

- [x] Physical
- [x] Emulator
- OS version(s): Android 8.1, Android 9

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [x] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2022-02-23 15:07 UTC, BillCarsonFr requested changes
Hello, I just had a quick look and I am a bit surprised on how it's done.
Given that there is already a method called when a task did fail to be sent in the eventSender, you could probably just add some listener mechanism and a the app layer you could then decide to show or not a notification (if the app is backgrounded or you are in a different room, smth like that).

But this still won't work if the app is killed or "dozed". For that to work you might want to have some sort of worker that check for unsent event and if it's there since too long you could then deschedule it and show a notification? This could avoid sending a message  sent long after you wanted (if you entered airplane mode for several hours?)

2022-02-23 15:17 UTC, ahmed-radhouane commented
> Hello, I just had a quick look and I am a bit surprised on how it's done. Given that there is already a method called when a task did fail to be sent in the eventSender, you could probably just add some listener mechanism and a the app layer you could then decide to show or not a notification (if the app is backgrounded or you are in a different room, smth like that).
> 
> But this still won't work if the app is killed or "dozed". For that to work you might want to have some sort of worker that check for unsent event and if it's there since too long you could then deschedule it and show a notification? This could avoid sending a message sent long after you wanted (if you entered airplane mode for several hours?)

> Hello thank you for the replay. 
the event sender tells me that there is a failed message but doesn't describe which kind of error was, a network , server or other which was asked to do to change the error message. There where I found a difficulties. If there is another method that could provide it. I will be grateful if you direct me toward. 

For the state killed app. I'm 100% percent ok with you. I guess a service is needed like the one used to intercept incoming calls. If you have other examples also that can help me as a reference for a solution. It's more than welcome. 

We can make a call or you can send me direct message, if you can that we discuss it in more details. 

Thank you

2022-02-24 13:30 UTC, bmarty commented
As discussed IRL, we shouls probably rely on an Android Service to display the notification, even if the app is killed.

I let you dig more in this lead and try to provide a better solution for this complexe use case. Thanks!

2022-06-16 14:05 UTC, bmarty commented
Closing as we will implement that maybe differently.

2022-06-16 14:05 UTC, closed without merging