Don't wrongly show non-space invites in the space panel
vector-im/element-android pull request #5731
Opened 2022-04-11 10:37 UTC by t3chguy

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Prevents invites to non-space non-null room types from showing up wrongly in the Space panel

## Motivation and context

## Screenshots / GIFs

|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/2403652/162721016-d4002bb2-01ed-4014-a576-0bbb6dd68b98.png)|![image](https://user-images.githubusercontent.com/2403652/162722406-46ab88a1-ad8a-4db7-ab9e-cb68a5553f86.png)|

## Tests

- Invited test account to video room
- Checked if invite was (wrongly) visible in the space panel

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): API 22

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] You've made a self review of your PR

2022-04-11 13:13 UTC, onurays requested changes
Is `gradle-wrapper.properties` changes accidental instead of changelog?

2022-04-12 11:38 UTC, onurays approved these changes
LGTM, but I have lack of knowledge about space :) Let me ask someone else to review too.

2022-04-12 12:02 UTC, BillCarsonFr requested changes
we could probably juste use `spaceSummaryQueryParams {`

2022-04-13 13:01 UTC, bmarty approved these changes
Thanks for the update

2022-04-13 13:01 UTC, merged