Added themed icon for Android 13
vector-im/element-android pull request #5936
Opened 2022-05-04 17:12 UTC by hanthor

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Added support for themed icons in Android 13. Folled guidance from here: https://developer.android.com/about/versions/13/features#themed-app-icons

## Motivation and context

Element current does not display with a themed icon in android 12 and 13

## Screenshots / GIFs

![image](https://user-images.githubusercontent.com/5840441/166741665-f52936d3-e551-4aac-a670-f5d3047c8db1.png)

## Tested devices

- [x ] Physical
- [x ] Emulator
- OS version(s): 13 beta 1

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

Signed-off-by: James Reilly <jreilly112@gmail.com>

2022-05-04 17:17 UTC, hanthor commented
I added the monochrome entry to both roung and regular icons due to the note here:

> Note: If android:roundIcon and android:icon are both in your manifest, you must either remove the reference to android:roundIcon or supply the monochrome icon in the drawable defined by the android:roundIcon attribute.

2022-05-11 14:19 UTC, bmarty requested changes
LGTM, thanks! Can you add a sign off please? Then I will be able to merge it.
See https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off

2022-05-11 15:24 UTC, hanthor commented
Signed off

2022-05-11 15:34 UTC, bmarty approved these changes

2022-05-11 15:34 UTC, merged