Make room avatar and name colors configurable based on theme
vector-im/element-android pull request #6045
Opened 2022-05-13 10:44 UTC by chagai95

## Type of change

- [X] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Make room avatar and name colors configurable based on theme. Only added dark and light for now.

## Motivation and context

## Screenshots / GIFs

## Tests

- Changed theme.
- Closed the app
- Reopened the app

## Tested devices

- [X] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [X] Changes has been tested on an Android device or Android emulator with API 21
- [X] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [X] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [X] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [X] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

Signed-off-by: Chagai Friedlander @me:chagai.website

2022-08-18 12:51 UTC, chagai95 commented
Just checking, did I do something wrong?

2022-10-04 15:56 UTC, bmarty requested changes
Thanks for the PR.
The code does not compile, nor the test. Can you check please?

Also please note that the default room and user color are shared across all Element Matrix client. Since there is no change on the value here, this is fine to accept this change.

2022-10-04 15:56 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MatrixItemColorProvider.kt
> +        private fun getUserColorByIndexColorInt(colorProvider: ColorProvider, index: Int): Int {
I think the fun above `getUserColorByIndex` could be removed.
And so the resources `R.color.element_name_0x` and `R.color.element_room_0x`.

2023-01-10 13:59 UTC, bmarty commented
Close as stale PR.

2023-01-10 13:59 UTC, closed without merging

2023-01-10 14:54 UTC, chagai95 commented
> Close as stale PR.

Sorry, I don't work with matrix anymore in my daily join and didn't find the time in my free time to get around to this.