Use stable endpoint for alias management
vector-im/element-android pull request #6288
Opened 2022-06-12 13:11 UTC by deepbluev7

This increases compatibility with homeservers and allows them to remove
Element Android specific workaround.

fixes #4830
see https://github.com/ruma/ruma/pull/936
see https://github.com/matrix-org/synapse/issues/8334
see https://github.com/matrix-org/synapse/pull/9224

Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>

 
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

## Motivation and context

## Screenshots / GIFs

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2022-06-12 14:18 UTC, bmarty requested changes
Thanks for the PR!
We will check that it's working well.
This line has to be modified as well: https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/network/ApiPath.kt#L165. May I ask you to do it please?

Thanks!

2022-06-12 16:05 UTC, deepbluev7 commented
Done, thank you for spotting that :3

2022-06-12 16:08 UTC, deepbluev7 commented
There is also some reference to the MSC here: https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/alias/GetRoomLocalAliasesTask.kt#L37

I'm not sure if that should be removed or it is a good idea to keep it, since the app might not check for r0.6.1 either?

2022-06-13 07:46 UTC, bmarty commented
> There is also some reference to the MSC here: https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/alias/GetRoomLocalAliasesTask.kt#L37
> 
> I'm not sure if that should be removed or it is a good idea to keep it, since the app might not check for r0.6.1 either?

Good point. I would vote to simply remove this comment.

2022-06-13 07:50 UTC, ouchadam commented
should the feature be guarded by a homeserver version check?

2022-06-13 07:53 UTC, deepbluev7 commented
@ouchadam The old one wasn't guarded by a homeserver version check either and this has been in synapse versions for about a year, I think. A homeserver version check in general would be good, but I think on that old servers a lot of other stuff is broken by now as well and I don't really know, where I would start adding such a check .-.

2022-06-13 07:58 UTC, ouchadam commented
agreed, it's not a blocker for this PR! thinking out loud, I wonder if we should have minimum supported homeserver version (if we don't already)

2022-06-16 08:27 UTC, fedrunov approved these changes

2022-06-29 10:47 UTC, deepbluev7 commented
Does this need anything from me?

2022-06-30 20:30 UTC, bmarty approved these changes

2022-06-30 20:30 UTC, merged