[Feature] Add privacy setting to disable personalized learning by the keyboard
vector-im/element-android pull request #6633
Opened 2022-07-24 15:44 UTC by Benjiko99

## Content

A new option has been added to the Privacy settings, which requests that the keyboard should not update any personalized data such as typing history and dictionary based on what the user typed.

## Motivation and context

Requesting that the keyboard minimize the amount of data it records about your private communications seems sensible for an encrypted messaging app.

It should disable the keyboard's personalized learning features, like adding your typed words into the personalized dictionary or storing the history of what you type. Some keyboards may not respect this setting. Signal messenger has this feature and missed it here.

## Screenshots

![image](https://user-images.githubusercontent.com/1648685/180654251-318b4227-a5ae-4bf0-8b4d-7186acbabfd6.png)

## Tests

- Use a keyboard that supports incognito mode, like Gboard
- In Element, enable "Incognito keyboard" in Settings->Security & Privacy->Other
- Enter a chat, focus the message input field, and the keyboard (in case of Gboard) will show an incognito icon in the top left corner

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): Android 12 (31)

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [x] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
    - [x] Signed-off-by: Tomáš Beňo <benjiko99@gmail.com>
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2022-07-25 08:40 UTC, bmarty requested changes
Thanks a lot for this Pull Request. 2 remarks, else LGTM!

2022-07-25 08:40 UTC, bmarty commented on vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
> +        composerEditText.setUseIncognitoKeyboard(vectorPreferences.useIncognitoKeyboard())
I am afraid that the `imeOptions` will be erased by the line 1530 just below, if `vectorPreferences.sendMessageWithEnter()` returns true.

Maybe on the same format than `setUseIncognitoKeyboard` create a new fun to (properly!) handle  `vectorPreferences.sendMessageWithEnter()` setting.

https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt#L1528

2022-09-07 09:18 UTC, kojid0 commented
Ping @Benjiko99 :-)

2022-09-25 13:11 UTC, Benjiko99 commented
All issues should be resolved now.

2022-10-04 15:37 UTC, bmarty approved these changes
LGTM, thanks for the update!

2022-10-04 16:22 UTC, merged