New App Layout Toolbar
vector-im/element-android pull request #6655
Opened 2022-07-27 14:20 UTC by ericdecanini

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Adds the new app layout toolbar hidden behind the New App Layout Enabled feature flag

## Motivation and context

Closes https://github.com/vector-im/element-android/issues/6580

Figma link: https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=2584%3A140337

This does not include behaviour when inside spaces or back navigation

## Screenshots / GIFs

| |Before|After|After (Collapsed)|
|-|-|-|-|
|Light|<img src="https://user-images.githubusercontent.com/20701752/181268723-09828847-ab85-4ef7-a353-c1a6a6d37bfc.png" width="200" />|<img src="https://user-images.githubusercontent.com/20701752/181269776-7608e6ec-63fe-45bb-9cb1-84a572f2c092.png" width="200" />|<img src="https://user-images.githubusercontent.com/20701752/181269886-9f5c0f95-197e-455e-bba9-1e94ba77fe93.png" width="200" />|
|Dark|<img src="https://user-images.githubusercontent.com/20701752/181268858-7dcb66c6-9b1e-445e-a660-9bd16654eb02.png" width="200" />|<img src="https://user-images.githubusercontent.com/20701752/181270229-fa4e32f2-1f96-44a3-b955-7d594f65f7a4.png" width="200" />|<img src="https://user-images.githubusercontent.com/20701752/181270347-5d444d7b-c5c9-421e-a40e-633e6326591c.png" width="200" />|
|Black|<img src="https://user-images.githubusercontent.com/20701752/181269341-c87a63c0-f9a2-44e3-8628-9f09fa45be74.png" width="200" />|<img src="https://user-images.githubusercontent.com/20701752/181270515-8e38fc05-4611-43ee-979e-e31486813348.png" width="200" />|<img src="https://user-images.githubusercontent.com/20701752/181270642-aa8fc0d2-0b7f-4729-9aeb-4cc56c8bab5b.png" width="200" />|

## Tests

- On a fresh install, access the cog at the bottom of the initial screen, go to Features and enable New App Layout
- Sign in
- See new app toolbar and ensure profile icon and settings show and react (on click) as expected

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2022-07-27 16:10 UTC, amshakal approved these changes
Looking good!

2022-07-28 13:47 UTC, kojid0 commented
![grafik](https://user-images.githubusercontent.com/24477557/181520500-129951c8-4f19-4fa3-b6e6-a0ef9003bd69.png)

Can't access figma since it not public, but are you sure that the graphics are correct? Why is there a division into DM and Rooms in the "All Chats" view?

2022-07-28 13:51 UTC, ericdecanini commented
You'd be right in thinking the diversion should no longer be there. We're tackling the new app layout bit by bit and hiding it behind the aforementioned feature flag until it's complete. Until then, the app as you see it will not have changed in the slightest

2022-08-02 11:21 UTC, fedrunov requested changes

2022-08-02 11:21 UTC, fedrunov commented on library/ui-styles/src/main/res/values/text_appearances.xml
> +    <style name="TextAppearance.Vector.Headline.Bold" parent="TextAppearance.MaterialComponents.Headline1">
Shouldn't we inherit from existing appearance?

2022-08-02 11:21 UTC, fedrunov commented on vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupStep3Fragment.kt
> +                    context = requireContext(),
where this change comes from?

2022-08-02 13:19 UTC, fedrunov approved these changes
LGTM

2022-08-02 15:44 UTC, merged