New App Layout FABs
vector-im/element-android pull request #6693
Opened 2022-07-29 13:47 UTC by ericdecanini

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Adds the new FABs to be used in the New App Layout. These will be hidden behind the New App Layout feature flag

## Motivation and context

Closes https://github.com/vector-im/element-android/issues/6582

## Screenshots / GIFs

## Tests

- Enable the New App Layout feature flag
- Sign in and see the FABs

Currently the FABs do not do anything on click. This will be handled in a separate PR

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2022-07-31 17:12 UTC, ericdecanini commented
LGTM

2022-07-31 17:13 UTC, ericdecanini commented
LGTM

2022-07-31 17:14 UTC, ericdecanini commented
LGTM

2022-07-31 17:14 UTC, ericdecanini commented
LGTM

2022-07-31 17:14 UTC, ericdecanini commented
LGTM

2022-07-31 17:15 UTC, ericdecanini commented
LGTM

2022-07-31 17:15 UTC, ericdecanini commented
LGTM

2022-07-31 17:15 UTC, ericdecanini commented
LGTM

2022-07-31 17:15 UTC, ericdecanini commented
LGTM

2022-07-31 17:15 UTC, ericdecanini commented
LGTM

2022-07-31 17:16 UTC, ericdecanini commented
LGTM

2022-08-01 09:44 UTC, amshakal approved these changes
Thank you!

We might change the icon for space switching based on feedback we recieve this week but the rest is perfect!

2022-08-02 11:13 UTC, fedrunov requested changes

2022-08-02 11:13 UTC, fedrunov commented on vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
> +            // Click action for open spaces modal goes here
worth to put here a todo with issue number

2022-08-02 11:13 UTC, fedrunov commented on vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
> +            // Click action for create chat modal goes here
missing implementation

2022-08-03 11:17 UTC, fedrunov approved these changes

2022-08-10 06:13 UTC, merged