filtered room list at home
vector-im/element-android pull request #6724
Opened 2022-08-03 11:13 UTC by fedrunov

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

## Motivation and context

part of https://github.com/vector-im/element-android/issues/6502
closes https://github.com/vector-im/element-android/issues/6505

## Screenshots / GIFs

|Light|Dark|Black|
|-|-|-|
|![Screenshot 2022-08-03 at 10 55 01](https://user-images.githubusercontent.com/66663241/182594291-03d16015-d901-4b0e-b22d-327c01c9b618.png)|![Screenshot 2022-08-03 at 10 54 34](https://user-images.githubusercontent.com/66663241/182594317-0dfbc9f6-9561-4d00-9289-aa15872f72b3.png)|![Screenshot 2022-08-03 at 10 54 48](https://user-images.githubusercontent.com/66663241/182594309-042fe5af-f003-4e1f-8cb9-8bdf2334e447.png)|

![output-optimised](https://user-images.githubusercontent.com/66663241/182594436-355ed122-252c-4ce2-895e-75ea5529a0db.gif)

2022-08-08 17:53 UTC, amshakal approved these changes

2022-08-09 12:38 UTC, ericdecanini requested changes
Small improvements, on top of conflicts to fix

2022-08-09 12:38 UTC, ericdecanini commented on library/ui-styles/src/main/res/values/styles_tablayout.xml
> +    <style name="Widget.App.TabLayout" parent="Widget.MaterialComponents.TabLayout">
Let's do `Widget.Vector.TabLayout` for consistent with other styles in the app

2022-08-09 12:38 UTC, ericdecanini commented on vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
> +        private val spaceStateHandler: SpaceStateHandler
Can we add a trailing comma here?

2022-08-10 13:30 UTC, yostyle approved these changes
LGTM

2022-08-10 13:30 UTC, yostyle commented on vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
> +        private val spaceStateHandler: SpaceStateHandler
```suggestion
        private val spaceStateHandler: SpaceStateHandler,
```

2022-08-11 10:26 UTC, ericdecanini requested changes
Implementation looks good but can we get a `.wip` changelog file please?

2022-08-11 13:13 UTC, ericdecanini approved these changes
Ty for the changes

2022-08-11 14:26 UTC, merged