Fixes crash when entering non ascii username during account creation
vector-im/element-android pull request #6736
Opened 2022-08-04 11:09 UTC by ouchadam

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Handles the exception throwing of the username availability check 

## Motivation and context

To avoid a crash when non ascii characters are used in the username during account creation

## Screenshots / GIFs

|Before|After|
|-|-|
|![before-non-ascii-account](https://user-images.githubusercontent.com/1848238/182831158-3469f5fc-5e1b-419d-b9d7-a58146d1faee.gif)|![after-ascii](https://user-images.githubusercontent.com/1848238/182831463-f060da44-5b5a-44dc-9332-a7719915a3e7.gif)|

## Tests

- In the account creation screen
- Enter non ascii characters in the username field

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 28

2022-08-08 11:28 UTC, ouchadam commented on vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
> +        runCatching { registrationWizard.registrationAvailable(userName) }.fold(
adding the `runCatching` is the fix

2022-08-09 10:38 UTC, jmartinesp requested changes
There is one weird behaviour when trying to go back:

[emoji_back.webm](https://user-images.githubusercontent.com/480955/183628156-f2af103e-66d6-4c37-bf2f-4abe77dc33ac.webm)

It seems like `checkUserNameAvailability` is getting called on that case too.

2022-08-09 10:49 UTC, jmartinesp approved these changes
It seems like the issue above was fixed in #6741. After rebasing develop and testing again, it's working fine.

2022-08-09 10:49 UTC, ouchadam commented
(We've spoke in the room) The backflow is handled by https://github.com/vector-im/element-android/pull/6741 this PR is slightly behind develop

2022-08-09 10:52 UTC, merged