Adds Space List Bottom Sheet
vector-im/element-android pull request #6749
Opened 2022-08-05 14:11 UTC by ericdecanini

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Adds Space List Bottom Sheet

## Motivation and context

Closes https://github.com/vector-im/element-android/issues/6499

Please take note of what is and isn't included in the issue

## Screenshots / GIFs

## Tests

- Enable the New App Layout feature flag
- Click on the open spaces FAB
- See the bottom sheet and try navigating between spaces
There is a known bug where the bottom sheet doesn't always measure properly. This will be addressed in TBA

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s): Android 12

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2022-08-05 15:21 UTC, amshakal approved these changes

2022-08-09 12:31 UTC, fedrunov requested changes
Looks good, but with some comments

2022-08-09 12:31 UTC, fedrunov commented on changelog.d/6749.feature
> +Adds space list bottom sheet for new app layout
I don't think we need to provide changelogs for features, which are not accessible for users 🤔

2022-08-10 06:17 UTC, ericdecanini commented on vector/src/main/java/im/vector/app/features/grouplist/NewHomeSpaceSummaryItem.kt
> +        holder.avatar.background = ContextCompat.getDrawable(holder.view.context, R.drawable.new_space_home_background)
No because we use the same XML for `NewSpaceSummaryItem`

2022-08-10 06:18 UTC, ericdecanini commented on vector/src/main/java/im/vector/app/features/grouplist/NewHomeSpaceSummaryItem.kt
> +                ColorUtils.setAlphaComponent(ThemeUtils.getColor(holder.view.context, R.attr.vctr_content_tertiary), (255 * 0.3).toInt()))
Same as above

2022-08-10 09:28 UTC, ericdecanini commented on changelog.d/6749.feature
> +Adds space list bottom sheet for new app layout
we should them but they should be `.wip`

2022-08-16 10:05 UTC, fedrunov approved these changes
LGTM

2022-08-17 08:51 UTC, merged