New App Layout: Adds New Chat Bottom Sheet
vector-im/element-android pull request #6801
Opened 2022-08-10 15:43 UTC by ericdecanini

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

## Motivation and context

Closes https://github.com/vector-im/element-android/issues/6717

This is the new way we differentiate between a new DM or a new create room chat when using the FAB on the main screen

## Screenshots / GIFs

<img width="200" alt="image" src="https://user-images.githubusercontent.com/20701752/183948612-2635b7d2-f098-4950-b3bb-7279353a68dc.png">

## Tests

- Enable the New App Layout Feature Flag
- Click the primary FAB
- See bottom sheet
- Ensure both options work

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s): Android 12

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2022-08-16 10:01 UTC, fedrunov requested changes

2022-08-16 10:01 UTC, fedrunov commented on vector/src/main/java/im/vector/app/features/home/room/list/home/NewChatBottomSheet.kt
> +            navigator.openCreateRoom(requireActivity(), "")
`initialName` param of `openCreateRoom` has default value, so you can just skip it

2022-08-18 09:40 UTC, fedrunov approved these changes
LGTM

2022-08-19 12:36 UTC, onurays commented on vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
> +            newChatBottomSheet.show(requireActivity().supportFragmentManager, NewChatBottomSheet.TAG)
Nit: Wdyt about creating the bottom sheet instance here instead of a class variable?

2022-08-19 12:37 UTC, onurays approved these changes
LGTM.

2022-08-19 13:22 UTC, merged