Remove hardcoded color on save button
vector-im/element-android pull request #8208
Opened 2023-03-04 21:15 UTC by jdauphant

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Save button background color is hardcoded. Now we use the theming colors instead.

Similar to : https://github.com/vector-im/element-android/pull/8142

## Motivation and context

## Screenshots / GIFs

## Tests

- Edit a message

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2023-03-04 21:32 UTC, jdauphant commented
:thinking: we may have the same problem with https://github.com/vector-im/element-android/blob/develop/vector/src/main/res/drawable/ic_composer_rich_mic_pressed.xml

2023-03-06 13:21 UTC, jonnyandrew approved these changes

2023-03-07 13:31 UTC, bmarty requested changes
Thanks for the change @jdauphant , can you add a sign-off so that we can merge the PR?

2023-03-08 00:07 UTC, jdauphant commented
@bmarty I have added the signoff in the pull request comment. Is that good ?

2023-03-09 14:06 UTC, merged