[Rich text editor] Add mentions
vector-im/element-android pull request #8440
Opened 2023-05-17 10:12 UTC by jonnyandrew

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Add the ability to mention users and rooms using the rich text editor.

## Motivation and context

- Closes vector-im/verticals-internal#86

## Screenshots / GIFs

[mentions.webm](https://github.com/vector-im/element-android/assets/4940864/ee98a7eb-da93-44c6-b1a3-759bba84ab00)

## Tests

- Enable rich text editor in labs settings
- Enter a room and autocomplete all of
  - A room mention
  - A user mention
  - A whole `@room` mention

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 13

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

2023-05-23 12:19 UTC, yostyle reviewed
The first mention does not work ![mention](https://github.com/vector-im/element-android/assets/1191674/b266442d-3f8b-4a8d-bb74-5ae78f1849a9)

2023-06-09 17:14 UTC, langleyd commented on vector/src/test/java/im/vector/app/features/home/room/detail/composer/mentions/PillDisplayHandlerTest.kt
> +    }
Thanks for the suggestions I think maybe PillDisplayHandler was not handling alias links.

2023-06-09 17:19 UTC, langleyd commented
@yostyle Addressed comments

@jonnyandrew Do you mind double checking my changes and merging next week if all looks good. Thanks!

2023-06-16 17:06 UTC, jonnyandrew commented
Sorry for the delay. Looking at the diff and [this line](https://github.com/vector-im/element-android/pull/8440/commits/f3db4a857af48ecc6ffe3f8782e80f6d06ef29ce#diff-2317e7b8b7691cdab886e762370723875e52418c9459b719f16a9f6f3bfecd8fR818), we may still have a problem because I don't think the rich text editor supports directly modifying the text in this way and I suspect the UI will lose sync with it's internal model.

I can reproduce some of these issues by doing the following:
- Type "Hello"
- Tap the username to add a mention so that text says "Hello `@user`"
- Type a few more words so that text says "Hello `@user` how are you doing?"
- Note that formatting buttons now have stopped working
- Note that backspace removes too much text

2023-06-20 08:14 UTC, jonnyandrew commented
@langleyd @yostyle the rich text editor doesn't support directly manipulating the text contents, which is the reason why we had issues inserting mentions by tapping a username.

I've fixed this in [`9d239bf`](https://github.com/vector-im/element-android/pull/8440/commits/9d239bf94da509006be576312c39762398ecd59f) by calling `setLink()` to add a mention instead.

2023-06-20 08:47 UTC, yostyle approved these changes
LGTM. Thanks
I detected some side effects when you mention a user by clicking on the displayname.

2023-06-20 08:48 UTC, langleyd approved these changes
Makes sense, thanks!

2023-06-20 09:13 UTC, yostyle requested changes
Completion is broken when we click on displayname.
![mention](https://github.com/vector-im/element-android/assets/1191674/f520b834-3d97-404f-b6a2-1a990d628d4a)

2023-06-21 08:37 UTC, langleyd commented
@yostyle Just a simple fix to add the space to match the old behaviour. One of the issues you highlighted can still occur if the users backspace and then tap the name but it is a bit less likely to happen and we have a fix coming for that in a separate upcoming PR.

2023-06-21 10:02 UTC, yostyle approved these changes
LGTM.

2023-06-21 10:26 UTC, merged